server:
  port: 8092
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted: packages=*